/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.survey.model.impl;

import com.jhu.cvrg.portal.survey.model.SurveyQuestionOption;
import com.jhu.cvrg.portal.survey.model.SurveyQuestionOptionModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the SurveyQuestionOption service. Represents a row in the &quot;JHU_SurveyQuestionOption&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.jhu.cvrg.portal.survey.model.SurveyQuestionOptionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SurveyQuestionOptionImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a survey question option model instance should use the {@link com.jhu.cvrg.portal.survey.model.SurveyQuestionOption} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see SurveyQuestionOptionImpl
 * @see com.jhu.cvrg.portal.survey.model.SurveyQuestionOption
 * @see com.jhu.cvrg.portal.survey.model.SurveyQuestionOptionModel
 * @generated
 */
public class SurveyQuestionOptionModelImpl extends BaseModelImpl<SurveyQuestionOption>
	implements SurveyQuestionOptionModel {
	public static final String TABLE_NAME = "JHU_SurveyQuestionOption";
	public static final Object[][] TABLE_COLUMNS = {
			{ "surveyQuestionOptionId", new Integer(Types.BIGINT) },
			{ "surveyQuestionId", new Integer(Types.BIGINT) },
			{ "question", new Integer(Types.VARCHAR) },
			{ "displayorder", new Integer(Types.INTEGER) }
		};
	public static final String TABLE_SQL_CREATE = "create table JHU_SurveyQuestionOption (surveyQuestionOptionId LONG not null primary key,surveyQuestionId LONG,question VARCHAR(75) null,displayorder INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table JHU_SurveyQuestionOption";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.jhu.cvrg.portal.survey.model.SurveyQuestionOption"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.jhu.cvrg.portal.survey.model.SurveyQuestionOption"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.jhu.cvrg.portal.survey.model.SurveyQuestionOption"));

	public SurveyQuestionOptionModelImpl() {
	}

	public long getPrimaryKey() {
		return _surveyQuestionOptionId;
	}

	public void setPrimaryKey(long pk) {
		setSurveyQuestionOptionId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_surveyQuestionOptionId);
	}

	public long getSurveyQuestionOptionId() {
		return _surveyQuestionOptionId;
	}

	public void setSurveyQuestionOptionId(long surveyQuestionOptionId) {
		_surveyQuestionOptionId = surveyQuestionOptionId;
	}

	public long getSurveyQuestionId() {
		return _surveyQuestionId;
	}

	public void setSurveyQuestionId(long surveyQuestionId) {
		_surveyQuestionId = surveyQuestionId;
	}

	public String getQuestion() {
		if (_question == null) {
			return StringPool.BLANK;
		}
		else {
			return _question;
		}
	}

	public void setQuestion(String question) {
		_question = question;
	}

	public int getDisplayorder() {
		return _displayorder;
	}

	public void setDisplayorder(int displayorder) {
		_displayorder = displayorder;
	}

	public SurveyQuestionOption toEscapedModel() {
		if (isEscapedModel()) {
			return (SurveyQuestionOption)this;
		}
		else {
			return (SurveyQuestionOption)Proxy.newProxyInstance(SurveyQuestionOption.class.getClassLoader(),
				new Class[] { SurveyQuestionOption.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					SurveyQuestionOption.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		SurveyQuestionOptionImpl surveyQuestionOptionImpl = new SurveyQuestionOptionImpl();

		surveyQuestionOptionImpl.setSurveyQuestionOptionId(getSurveyQuestionOptionId());

		surveyQuestionOptionImpl.setSurveyQuestionId(getSurveyQuestionId());

		surveyQuestionOptionImpl.setQuestion(getQuestion());

		surveyQuestionOptionImpl.setDisplayorder(getDisplayorder());

		return surveyQuestionOptionImpl;
	}

	public int compareTo(SurveyQuestionOption surveyQuestionOption) {
		long pk = surveyQuestionOption.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SurveyQuestionOption surveyQuestionOption = null;

		try {
			surveyQuestionOption = (SurveyQuestionOption)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = surveyQuestionOption.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{surveyQuestionOptionId=");
		sb.append(getSurveyQuestionOptionId());
		sb.append(", surveyQuestionId=");
		sb.append(getSurveyQuestionId());
		sb.append(", question=");
		sb.append(getQuestion());
		sb.append(", displayorder=");
		sb.append(getDisplayorder());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.jhu.cvrg.portal.survey.model.SurveyQuestionOption");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>surveyQuestionOptionId</column-name><column-value><![CDATA[");
		sb.append(getSurveyQuestionOptionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>surveyQuestionId</column-name><column-value><![CDATA[");
		sb.append(getSurveyQuestionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>question</column-name><column-value><![CDATA[");
		sb.append(getQuestion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>displayorder</column-name><column-value><![CDATA[");
		sb.append(getDisplayorder());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _surveyQuestionOptionId;
	private long _surveyQuestionId;
	private String _question;
	private int _displayorder;
	private transient ExpandoBridge _expandoBridge;
}