/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.survey.model.impl;

import com.jhu.cvrg.portal.survey.model.SurveyQuestion;
import com.jhu.cvrg.portal.survey.model.SurveyQuestionModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the SurveyQuestion service. Represents a row in the &quot;JHU_SurveyQuestion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.jhu.cvrg.portal.survey.model.SurveyQuestionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SurveyQuestionImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a survey question model instance should use the {@link com.jhu.cvrg.portal.survey.model.SurveyQuestion} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see SurveyQuestionImpl
 * @see com.jhu.cvrg.portal.survey.model.SurveyQuestion
 * @see com.jhu.cvrg.portal.survey.model.SurveyQuestionModel
 * @generated
 */
public class SurveyQuestionModelImpl extends BaseModelImpl<SurveyQuestion>
	implements SurveyQuestionModel {
	public static final String TABLE_NAME = "JHU_SurveyQuestion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "surveyQuestionId", new Integer(Types.BIGINT) },
			{ "surveyId", new Integer(Types.BIGINT) },
			{ "question", new Integer(Types.VARCHAR) },
			{ "type_", new Integer(Types.INTEGER) },
			{ "displayorder", new Integer(Types.INTEGER) }
		};
	public static final String TABLE_SQL_CREATE = "create table JHU_SurveyQuestion (surveyQuestionId LONG not null primary key,surveyId LONG,question VARCHAR(75) null,type_ INTEGER,displayorder INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table JHU_SurveyQuestion";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.jhu.cvrg.portal.survey.model.SurveyQuestion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.jhu.cvrg.portal.survey.model.SurveyQuestion"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.jhu.cvrg.portal.survey.model.SurveyQuestion"));

	public SurveyQuestionModelImpl() {
	}

	public long getPrimaryKey() {
		return _surveyQuestionId;
	}

	public void setPrimaryKey(long pk) {
		setSurveyQuestionId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_surveyQuestionId);
	}

	public long getSurveyQuestionId() {
		return _surveyQuestionId;
	}

	public void setSurveyQuestionId(long surveyQuestionId) {
		_surveyQuestionId = surveyQuestionId;
	}

	public long getSurveyId() {
		return _surveyId;
	}

	public void setSurveyId(long surveyId) {
		_surveyId = surveyId;
	}

	public String getQuestion() {
		if (_question == null) {
			return StringPool.BLANK;
		}
		else {
			return _question;
		}
	}

	public void setQuestion(String question) {
		_question = question;
	}

	public int getType() {
		return _type;
	}

	public void setType(int type) {
		_type = type;
	}

	public int getDisplayorder() {
		return _displayorder;
	}

	public void setDisplayorder(int displayorder) {
		_displayorder = displayorder;
	}

	public SurveyQuestion toEscapedModel() {
		if (isEscapedModel()) {
			return (SurveyQuestion)this;
		}
		else {
			return (SurveyQuestion)Proxy.newProxyInstance(SurveyQuestion.class.getClassLoader(),
				new Class[] { SurveyQuestion.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					SurveyQuestion.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		SurveyQuestionImpl surveyQuestionImpl = new SurveyQuestionImpl();

		surveyQuestionImpl.setSurveyQuestionId(getSurveyQuestionId());

		surveyQuestionImpl.setSurveyId(getSurveyId());

		surveyQuestionImpl.setQuestion(getQuestion());

		surveyQuestionImpl.setType(getType());

		surveyQuestionImpl.setDisplayorder(getDisplayorder());

		return surveyQuestionImpl;
	}

	public int compareTo(SurveyQuestion surveyQuestion) {
		long pk = surveyQuestion.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SurveyQuestion surveyQuestion = null;

		try {
			surveyQuestion = (SurveyQuestion)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = surveyQuestion.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{surveyQuestionId=");
		sb.append(getSurveyQuestionId());
		sb.append(", surveyId=");
		sb.append(getSurveyId());
		sb.append(", question=");
		sb.append(getQuestion());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", displayorder=");
		sb.append(getDisplayorder());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.jhu.cvrg.portal.survey.model.SurveyQuestion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>surveyQuestionId</column-name><column-value><![CDATA[");
		sb.append(getSurveyQuestionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>surveyId</column-name><column-value><![CDATA[");
		sb.append(getSurveyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>question</column-name><column-value><![CDATA[");
		sb.append(getQuestion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>displayorder</column-name><column-value><![CDATA[");
		sb.append(getDisplayorder());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _surveyQuestionId;
	private long _surveyId;
	private String _question;
	private int _type;
	private int _displayorder;
	private transient ExpandoBridge _expandoBridge;
}