/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.survey.model.impl;

import com.jhu.cvrg.portal.survey.model.SurveyAnswer;
import com.jhu.cvrg.portal.survey.model.SurveyAnswerModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the SurveyAnswer service. Represents a row in the &quot;JHU_SurveyAnswer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.jhu.cvrg.portal.survey.model.SurveyAnswerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SurveyAnswerImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a survey answer model instance should use the {@link com.jhu.cvrg.portal.survey.model.SurveyAnswer} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see SurveyAnswerImpl
 * @see com.jhu.cvrg.portal.survey.model.SurveyAnswer
 * @see com.jhu.cvrg.portal.survey.model.SurveyAnswerModel
 * @generated
 */
public class SurveyAnswerModelImpl extends BaseModelImpl<SurveyAnswer>
	implements SurveyAnswerModel {
	public static final String TABLE_NAME = "JHU_SurveyAnswer";
	public static final Object[][] TABLE_COLUMNS = {
			{ "surveyAnswerId", new Integer(Types.BIGINT) },
			{ "surveyQuestionId", new Integer(Types.BIGINT) },
			{ "surveyId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "answer", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table JHU_SurveyAnswer (surveyAnswerId LONG not null primary key,surveyQuestionId LONG,surveyId LONG,userId LONG,answer VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table JHU_SurveyAnswer";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.jhu.cvrg.portal.survey.model.SurveyAnswer"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.jhu.cvrg.portal.survey.model.SurveyAnswer"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.jhu.cvrg.portal.survey.model.SurveyAnswer"));

	public SurveyAnswerModelImpl() {
	}

	public long getPrimaryKey() {
		return _surveyAnswerId;
	}

	public void setPrimaryKey(long pk) {
		setSurveyAnswerId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_surveyAnswerId);
	}

	public long getSurveyAnswerId() {
		return _surveyAnswerId;
	}

	public void setSurveyAnswerId(long surveyAnswerId) {
		_surveyAnswerId = surveyAnswerId;
	}

	public long getSurveyQuestionId() {
		return _surveyQuestionId;
	}

	public void setSurveyQuestionId(long surveyQuestionId) {
		_surveyQuestionId = surveyQuestionId;
	}

	public long getSurveyId() {
		return _surveyId;
	}

	public void setSurveyId(long surveyId) {
		_surveyId = surveyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public String getAnswer() {
		if (_answer == null) {
			return StringPool.BLANK;
		}
		else {
			return _answer;
		}
	}

	public void setAnswer(String answer) {
		_answer = answer;
	}

	public SurveyAnswer toEscapedModel() {
		if (isEscapedModel()) {
			return (SurveyAnswer)this;
		}
		else {
			return (SurveyAnswer)Proxy.newProxyInstance(SurveyAnswer.class.getClassLoader(),
				new Class[] { SurveyAnswer.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					SurveyAnswer.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		SurveyAnswerImpl surveyAnswerImpl = new SurveyAnswerImpl();

		surveyAnswerImpl.setSurveyAnswerId(getSurveyAnswerId());

		surveyAnswerImpl.setSurveyQuestionId(getSurveyQuestionId());

		surveyAnswerImpl.setSurveyId(getSurveyId());

		surveyAnswerImpl.setUserId(getUserId());

		surveyAnswerImpl.setAnswer(getAnswer());

		return surveyAnswerImpl;
	}

	public int compareTo(SurveyAnswer surveyAnswer) {
		long pk = surveyAnswer.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SurveyAnswer surveyAnswer = null;

		try {
			surveyAnswer = (SurveyAnswer)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = surveyAnswer.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{surveyAnswerId=");
		sb.append(getSurveyAnswerId());
		sb.append(", surveyQuestionId=");
		sb.append(getSurveyQuestionId());
		sb.append(", surveyId=");
		sb.append(getSurveyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", answer=");
		sb.append(getAnswer());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.jhu.cvrg.portal.survey.model.SurveyAnswer");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>surveyAnswerId</column-name><column-value><![CDATA[");
		sb.append(getSurveyAnswerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>surveyQuestionId</column-name><column-value><![CDATA[");
		sb.append(getSurveyQuestionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>surveyId</column-name><column-value><![CDATA[");
		sb.append(getSurveyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>answer</column-name><column-value><![CDATA[");
		sb.append(getAnswer());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _surveyAnswerId;
	private long _surveyQuestionId;
	private long _surveyId;
	private long _userId;
	private String _userUuid;
	private String _answer;
	private transient ExpandoBridge _expandoBridge;
}