/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.survey.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Survey service. Represents a row in the &quot;JHU_Survey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jhu.cvrg.portal.survey.model.impl.SurveyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jhu.cvrg.portal.survey.model.impl.SurveyImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a survey model instance should use the {@link Survey} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see Survey
 * @see com.jhu.cvrg.portal.survey.model.impl.SurveyImpl
 * @see com.jhu.cvrg.portal.survey.model.impl.SurveyModelImpl
 * @generated
 */
public interface SurveyModel extends BaseModel<Survey> {
	/**
	 * Gets the primary key of this survey.
	 *
	 * @return the primary key of this survey
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey
	 *
	 * @param pk the primary key of this survey
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the survey id of this survey.
	 *
	 * @return the survey id of this survey
	 */
	public long getSurveyId();

	/**
	 * Sets the survey id of this survey.
	 *
	 * @param surveyId the survey id of this survey
	 */
	public void setSurveyId(long surveyId);

	/**
	 * Gets the community id of this survey.
	 *
	 * @return the community id of this survey
	 */
	public long getCommunityId();

	/**
	 * Sets the community id of this survey.
	 *
	 * @param communityId the community id of this survey
	 */
	public void setCommunityId(long communityId);

	/**
	 * Gets the survey name of this survey.
	 *
	 * @return the survey name of this survey
	 */
	@AutoEscape
	public String getSurveyName();

	/**
	 * Sets the survey name of this survey.
	 *
	 * @param surveyName the survey name of this survey
	 */
	public void setSurveyName(String surveyName);

	/**
	 * Gets a copy of this survey as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Survey toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Survey survey);

	public int hashCode();

	public String toString();

	public String toXmlString();
}