/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.survey.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SurveyQuestionOption service. Represents a row in the &quot;JHU_SurveyQuestionOption&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jhu.cvrg.portal.survey.model.impl.SurveyQuestionOptionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jhu.cvrg.portal.survey.model.impl.SurveyQuestionOptionImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a survey question option model instance should use the {@link SurveyQuestionOption} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see SurveyQuestionOption
 * @see com.jhu.cvrg.portal.survey.model.impl.SurveyQuestionOptionImpl
 * @see com.jhu.cvrg.portal.survey.model.impl.SurveyQuestionOptionModelImpl
 * @generated
 */
public interface SurveyQuestionOptionModel extends BaseModel<SurveyQuestionOption> {
	/**
	 * Gets the primary key of this survey question option.
	 *
	 * @return the primary key of this survey question option
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey question option
	 *
	 * @param pk the primary key of this survey question option
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the survey question option id of this survey question option.
	 *
	 * @return the survey question option id of this survey question option
	 */
	public long getSurveyQuestionOptionId();

	/**
	 * Sets the survey question option id of this survey question option.
	 *
	 * @param surveyQuestionOptionId the survey question option id of this survey question option
	 */
	public void setSurveyQuestionOptionId(long surveyQuestionOptionId);

	/**
	 * Gets the survey question id of this survey question option.
	 *
	 * @return the survey question id of this survey question option
	 */
	public long getSurveyQuestionId();

	/**
	 * Sets the survey question id of this survey question option.
	 *
	 * @param surveyQuestionId the survey question id of this survey question option
	 */
	public void setSurveyQuestionId(long surveyQuestionId);

	/**
	 * Gets the question of this survey question option.
	 *
	 * @return the question of this survey question option
	 */
	@AutoEscape
	public String getQuestion();

	/**
	 * Sets the question of this survey question option.
	 *
	 * @param question the question of this survey question option
	 */
	public void setQuestion(String question);

	/**
	 * Gets the displayorder of this survey question option.
	 *
	 * @return the displayorder of this survey question option
	 */
	public int getDisplayorder();

	/**
	 * Sets the displayorder of this survey question option.
	 *
	 * @param displayorder the displayorder of this survey question option
	 */
	public void setDisplayorder(int displayorder);

	/**
	 * Gets a copy of this survey question option as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public SurveyQuestionOption toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SurveyQuestionOption surveyQuestionOption);

	public int hashCode();

	public String toString();

	public String toXmlString();
}