/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.jhu.cvrg.portal.survey.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SurveyQuestion service. Represents a row in the &quot;JHU_SurveyQuestion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.jhu.cvrg.portal.survey.model.impl.SurveyQuestionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.jhu.cvrg.portal.survey.model.impl.SurveyQuestionImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a survey question model instance should use the {@link SurveyQuestion} interface instead.
 * </p>
 *
 * @author Chris Jurado
 * @see SurveyQuestion
 * @see com.jhu.cvrg.portal.survey.model.impl.SurveyQuestionImpl
 * @see com.jhu.cvrg.portal.survey.model.impl.SurveyQuestionModelImpl
 * @generated
 */
public interface SurveyQuestionModel extends BaseModel<SurveyQuestion> {
	/**
	 * Gets the primary key of this survey question.
	 *
	 * @return the primary key of this survey question
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey question
	 *
	 * @param pk the primary key of this survey question
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the survey question id of this survey question.
	 *
	 * @return the survey question id of this survey question
	 */
	public long getSurveyQuestionId();

	/**
	 * Sets the survey question id of this survey question.
	 *
	 * @param surveyQuestionId the survey question id of this survey question
	 */
	public void setSurveyQuestionId(long surveyQuestionId);

	/**
	 * Gets the survey id of this survey question.
	 *
	 * @return the survey id of this survey question
	 */
	public long getSurveyId();

	/**
	 * Sets the survey id of this survey question.
	 *
	 * @param surveyId the survey id of this survey question
	 */
	public void setSurveyId(long surveyId);

	/**
	 * Gets the question of this survey question.
	 *
	 * @return the question of this survey question
	 */
	@AutoEscape
	public String getQuestion();

	/**
	 * Sets the question of this survey question.
	 *
	 * @param question the question of this survey question
	 */
	public void setQuestion(String question);

	/**
	 * Gets the type of this survey question.
	 *
	 * @return the type of this survey question
	 */
	public int getType();

	/**
	 * Sets the type of this survey question.
	 *
	 * @param type the type of this survey question
	 */
	public void setType(int type);

	/**
	 * Gets the displayorder of this survey question.
	 *
	 * @return the displayorder of this survey question
	 */
	public int getDisplayorder();

	/**
	 * Sets the displayorder of this survey question.
	 *
	 * @param displayorder the displayorder of this survey question
	 */
	public void setDisplayorder(int displayorder);

	/**
	 * Gets a copy of this survey question as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public SurveyQuestion toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SurveyQuestion surveyQuestion);

	public int hashCode();

	public String toString();

	public String toXmlString();
}